#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requests-kerberos
Version  : 0.8.0
Release  : 6
URL      : https://pypi.python.org/packages/source/r/requests-kerberos/requests-kerberos-0.8.0.tar.gz
Source0  : https://pypi.python.org/packages/source/r/requests-kerberos/requests-kerberos-0.8.0.tar.gz
Summary  : A Kerberos authentication handler for python-requests
Group    : Development/Tools
License  : HPND
Requires: requests-kerberos-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
requests Kerberos/GSSAPI authentication library
===============================================

%package python
Summary: python components for the requests-kerberos package.
Group: Default

%description python
python components for the requests-kerberos package.


%prep
%setup -q -n requests-kerberos-0.8.0

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
